### PR TITLE
Create Whatisasmartcontract.md

### PR DESCRIPTION
**Pull request by Cosmopusk**
New article about smart contracts

### CODE REVIEW

**Review by serejandmyself — CHANGES_REQUESTED** [review]
seems to have no links, is that mean t to be like that?

**Comment by Cosmopusk** [comment]
yes, im added  link)

**Review by serejandmyself — CHANGES_REQUESTED** [review]
But still no links... i dont mean the links to our services (that is cool). I mean links to the content inside of the article

**Review by serejandmyself — CHANGES_REQUESTED** [review]
Missing one line for me. A smart contract is nothing more than a programmable behavior of the chain or even simpler, its a programmable behavior

**Comment by Cosmopusk** [comment]
added a line

**Review by Pnumek — APPROVED** [review]

**Review by spotlessmind1 — APPROVED** [review]

**Pull request merged**
