### PR TITLE
Create evmosupdate.md

### PR DESCRIPTION
**Pull request by spotlessmind1**
we have wrote news about evmos

### CODE REVIEW

**Review by serejandmyself — CHANGES_REQUESTED** [review]
- $ not for github

- lnks need to be embedded

- title needs to be changed

**Review by serejandmyself — CHANGES_REQUESTED** [review]
- Links are still not embedded

- Citizen Cosmos - your trusted validator: can we think of a new tag line for our validator?

**Comment by Cosmopusk** [comment]
I added links and changed tag line. What do you think?

**Review by serejandmyself — CHANGES_REQUESTED** [review]
Links are not embedded again

**Comment by Cosmopusk** [comment]
added links

**Pull request closed without merging**
