### PR TITLE
Create Tokensandcoins.md

### PR DESCRIPTION
**Pull request by Cosmopusk**
New article about tokens and coins

### CODE REVIEW

**Review by serejandmyself — CHANGES_REQUESTED** [review]
- seems that much better styling can be applied with some simple markdown

**Comment by Cosmopusk** [comment]
corrected

**Review by serejandmyself — CHANGES_REQUESTED** [review]
Please embed link and change the tag line =) 

Citizen Cosmos - your trusted validator.

Staking with us - https://www.citizencosmos.space/staking

**Comment by Cosmopusk** [comment]
I added links and changed tag line. What do you think?

**Review by serejandmyself — DISMISSED** [review]
Can we please add somewhere that this is all super subjective and at the end of the day its not what matters?

**Review by Pnumek — APPROVED** [review]

**Review by spotlessmind1 — APPROVED** [review]

**Pull request merged**
